### ISSUE TITLE
Docs: Build & Install

### ISSUE THREAD

**Issue by MitchellHayes** [tzfx/owrn#13]
Update readme with build and install instructions.

**Comment by tzfx** [comment]
I worked in the suggested ios changes from your branch, however we probably need to include android instructions. I was able to get a sim up and running without too much hassle but I need to borrow someone's phone for #9  :P

**Comment by tzfx** [comment]
#21 Updated the readme instructions for android. Feels like it's in a good place now. Feel free to check out the README and see if anything is missing.
